//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/inputSetting/MainInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MainInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MainInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MainInput"",
    ""maps"": [
        {
            ""name"": ""MoveStates"",
            ""id"": ""28d53230-7018-45a0-bf9e-e5fed3782a41"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""195b8293-7b83-46f2-891c-916cb3ab12af"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": ""Normalize(min=-1,max=1),Clamp(min=-1,max=1)"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c5cb66b2-b00d-4efd-8714-df38e1c80f88"",
                    ""path"": ""<Touchscreen>/delta/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d91c4695-c894-495d-9d59-5fa81d2f1371"",
                    ""path"": ""<Pointer>/delta/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MoveStates
        m_MoveStates = asset.FindActionMap("MoveStates", throwIfNotFound: true);
        m_MoveStates_Move = m_MoveStates.FindAction("Move", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MoveStates
    private readonly InputActionMap m_MoveStates;
    private List<IMoveStatesActions> m_MoveStatesActionsCallbackInterfaces = new List<IMoveStatesActions>();
    private readonly InputAction m_MoveStates_Move;
    public struct MoveStatesActions
    {
        private @MainInput m_Wrapper;
        public MoveStatesActions(@MainInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_MoveStates_Move;
        public InputActionMap Get() { return m_Wrapper.m_MoveStates; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MoveStatesActions set) { return set.Get(); }
        public void AddCallbacks(IMoveStatesActions instance)
        {
            if (instance == null || m_Wrapper.m_MoveStatesActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MoveStatesActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IMoveStatesActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IMoveStatesActions instance)
        {
            if (m_Wrapper.m_MoveStatesActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMoveStatesActions instance)
        {
            foreach (var item in m_Wrapper.m_MoveStatesActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MoveStatesActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MoveStatesActions @MoveStates => new MoveStatesActions(this);
    public interface IMoveStatesActions
    {
        void OnMove(InputAction.CallbackContext context);
    }
}
